### ISSUE TITLE
.off can modify the _events array before the rest of the .on listeners are apply'd

### ISSUE THREAD

**Issue by doranen** [nrn/nee#1]
calling .off('event', handlerX) synchronously within the invocation of handlerX during an 'event' emit will modify the _.events['event'] array, removing that handler, but also skipping the next handler in line.

**Comment by nrn** [comment]
Doh! Thanks. Not sure how I want to handle this. Either listeners needs to return a copy instead of a reference, or off needs copy instead of modify...
